package ru.nikfirs.android.traveltracker.feature.home.fake

import kotlinx.coroutines.test.runTest
import ru.nikfirs.android.traveltracker.core.domain.model.testTrip
import ru.nikfirs.android.traveltracker.feature.home.domain.usecase.trip.SaveTripUseCase
import kotlin.test.Test
import kotlin.test.assertEquals

class SaveTripUseCaseTest {

    @Test
    fun `invoke returns id generated by repository`() = runTest {
        // given
        val expected = 1L
        // when
        val result = SaveTripUseCase(FakeTripRepository()).invoke(testTrip())
        // then
        assertEquals(expected, result)
    }

    @Test
    fun `invoke stores trip in repository`() = runTest {
        val repository = FakeTripRepository()
        // given
        val expected = listOf(testTrip(id = 1))
        // when
        val newTrip = testTrip().copy(id = 0)
        SaveTripUseCase(repository)(newTrip)
        val result = repository.savedTrips
        // then
        assertEquals(expected, result)
    }
}